### ISSUE TITLE
"price" is missing from words.txt

### ISSUE THREAD

**Issue by miketashcorpnet** [dwyl/english-words#118]
Subject says it all. Several compound words are found, but not "price" itself

New to GitHub, not sure how to contribute yet. Filing an issue to track it. 

% grep price words.txt
Caprice
caprices
counter-price
cut-price
half-price
Haltemprice
high-priced
low-priced
miniprice
miniprices
misprice
one-price
outprice
outpriced
outprices
overprice
overpriced
overprices
popular-priced
preprice
prepriced
priceable
priceably
price-cut
price-cutter
price-cutting
priced
price-deciding
price-enhancing
pricefixing
price-fixing
pricey
priceite
priceless
pricelessly
pricelessness
price-lowering
pricemaker
pricer
price-raising
price-reducing
pricers
price-ruling
prices
price-stabilizing
reprice
repriced
reprices
underprice
underpriced
underprices
uneven-priced
unpriceably
unpriced
well-priced

**Comment by adsteel** [comment]
Try this, it's in there, just capitalized:

```bash
cat words.txt | grep -i ^price
```

**Comment by miketashcorpnet** [comment]
Fair enough. Thanks for spotting it.
