### ISSUE TITLE
Cleanup needed

### ISSUE THREAD

**Issue by Awe23123** [dwyl/english-words#13]
I was scrolling through the list and I found "Ultra-englishUltra-french". I suppose this is not a word?

**Comment by nelsonic** [comment]
@Awe23123 thanks for reporting this! 
agreed. doesn't need to be in the list. 😞 
please remove and send us a Pull Request. 👍

**Comment by Awe23123** [comment]
I also found that some of the words seem not to belong to English words, like:
"vCeskoslovensko"
"vCechy"
I tried to google their meanings but I found nothing.

Some words also seem to be missing hyphens, like:
"semiRussian"
"proAfrican"

Should I make another pull request for these?
