### ISSUE TITLE
missing words and plurals, a handful of misspellings, and incorrectly placed hyphens

### ISSUE THREAD

**Issue by StormyPluto3865** [dwyl/english-words#172]
`cock-a-doodle--dooed`, `what-you-may--call-it`, and `cock-a-doodle--dooing` probably shouldn't have two hyphens in a row.
`capacitativly` is misspelled
`quatuorvirate` (quattuorvirate) is possibly a typo as well as `septemdecillion` (septendecillion)

In addition, there are a lot of missing words and plurals:
[missing words.txt](https://github.com/dwyl/english-words/files/11171423/missing.words.txt)

**Comment by mosamaasghar** [comment]
You are right there are very basic mistakes[,](https://englishbos.com/100-basic-vocabulary-words-in-english-pdf/) that should be solved at the earliest.

**Comment by CuriousKit** [comment]
I've also noticed that "boxkeepers" is missing (the singular form is present) from both words.txt and words_alpha.txt.
