### ISSUE TITLE
Double quotes used instead of apostrophe

### ISSUE THREAD

**Issue by darriuk** [dwyl/english-words#18]
In the following words:
he"ll
it"ll
hain"t

**Comment by nelsonic** [comment]
hi @darriuk please fix with PR if you can. 👍

**Comment by tomprogers** [comment]
This ticket should probably be closed, as a patch addressing it has merged to master.

**Comment by nadavb** [comment]
What about missing apostrophe-included words?

**Comment by nelsonic** [comment]
@nadavb worth opening a separate issue for those. (Please/thanks!)

As @tomprogers noted above the OP's issue was resolved.
