### ISSUE TITLE
A lot of gibberish

### ISSUE THREAD

**Issue by francogrex** [dwyl/english-words#189]
There are many more gibberish words than any real english

**Comment by erondpowell** [comment]
@francogrex I'm building a script to validate this list and extract only true English words you'd find in the dictionary. 

Then I'm going to open source that... Once complete, it won't have every English word ever, and there *might* be a number of "artifacts" (such as slang, proper nouns that belong in an encyclopediam, or abbreviations), but it will be something that can be improved on.

If you're interested, I can ping you when it is ready (some time this month).

**Comment by nelsonic** [comment]
@francogrex this is simply not true. 
Yes, there are too many non-words that need to be removed,
but the vast majority are valid English words. 

This issue does not identify an actual problem So closing. Thanks.
