### ISSUE TITLE
UK english to US english words text file 

### ISSUE THREAD

**Issue by Roeegg2** [dwyl/english-words#198]
I've been translating US to UK English and vice versa for a project, and I've noticed there is no reliable dictionary containing all (or at least most) of the words which are spelled differently.

I've spent a whole day just creating a dictionary for that, (and as far as I know) I have created the largest one.
It is not 100% complete, but it does contain the most of such words.
Is this something that would be of value to this repo?

**Comment by Roeegg2** [comment]
?

**Comment by go-to-mjrecent-on-TG** [comment]
Can you share it?

**Comment by Roeegg2** [comment]
Sure, I'll open a PR

**Comment by nelsonic** [comment]
PR #202 merged. ✅
