### ISSUE TITLE
words.txt doesn't contain the word "to".

### ISSUE THREAD

**Issue by gutrix** [dwyl/english-words#23]

**Comment by SwiftsNamesake** [comment]
It does, but it's uppercase. Not sure if that's intentional (the data was scraped from various sources, I believe).

**Comment by gutrix** [comment]
Right, I ran into problems when I was using this list in a spelling checker that was case sensitive. That list has multiple small words that aren't included. I personally believe this should be mentioned somewhere in README (maybe saying one might need to use both words_alpha and words to include most words).

**Comment by simonsteele24** [comment]
Fixed this issue at #56

**Comment by scottchiefbaker** [comment]
This can be closed as it's been merged already.

**Comment by nelsonic** [comment]
@scottchiefbaker thanks for the reminder. (_wish people would close their own issues ..._) 😉
