### ISSUE TITLE
I want to make a dictionary with increasing values instead of mapping every value as 1

### ISSUE THREAD

**Issue by khadeerusman** [dwyl/english-words#29]
Pls help me with python code

**Comment by nelsonic** [comment]
@khadeerusman have you had a look at: https://docs.python.org/2/tutorial/datastructures.html#dictionaries ?

**Comment by tomprogers** [comment]
This question is probably best handled by [StackOverflow](https://stackoverflow.com/), where they will likely point you to the Python docs.

**Comment by tomprogers** [comment]
This ticket should probably be closed.
