### ISSUE TITLE
words.txt doesn't contain lowercased "the"?

### ISSUE THREAD

**Issue by nadavb** [dwyl/english-words#52]
words.txt doesn't contain lowercased "the"?

**Comment by simonsteele24** [comment]
Expanding on this, it would also be nice to add articles to words.txt that do not have hyphens or periods next to them. For example, currently words.txt has "the-" but "the"

**Comment by nelsonic** [comment]
@nadavb / @simonsteele24 if you have time, please create a Pull Request with the desired change.

**Comment by nelsonic** [comment]
@simonsteele24 thanks for adding the words. #55 👍
