### ISSUE TITLE
"zoogrpahy" is a mispelling of zoography which is already in the table

### ISSUE THREAD

**Issue by Borthralla** [dwyl/english-words#60]
Please remove "zoogrpahy" from the list since it's not a word.

**Comment by nelsonic** [comment]
@Borthralla thanks for reporting this typo. 👍 
If you have time, please _remove_ the incorrect word via Pull Request.
Thank you!

**Comment by Borthralla** [comment]
Made a PR:
https://github.com/dwyl/english-words/pull/61

**Comment by nelsonic** [comment]
@Borthralla thanks again for fixing it so quickly. 👍
