### ISSUE TITLE
Should words_dictionary.json be a json array ?

### ISSUE THREAD

**Issue by sushantsahu1987** [dwyl/english-words#62]
Is there any reason why the content of words_dictionary.json isn't a JSON array ?

For e.g instead of it being
{  "aalii": 1,
  "aaliis": 1,
  "aals": 1 } it could be ["aalii", "aaliis", "aals"]

**Comment by scottchiefbaker** [comment]
If it's a hash it makes look ups really easy.

    if ($hash['hamburger']) { ... }

Is much faster than 

    if (in_array($dictionary, "hamburger")) { ... }

I can see reasons for wanting it both ways, but I imagine the primary use of this is as a lookup table. Besides it's **really** easy to convert it to an array if that's what you want.

**Comment by nelsonic** [comment]
@sushantsahu1987 thanks for opening this question. Curiosity/questioning is always good. 👍 

Having the data in .json is a convenience that allows people to load the data into any programming language/runtime (_everything supports .json_) and then the data structure can _easily_ be converted into a hash, map, array etc. Some languages don't handle _mega_ arrays very well. Also there would be "_debate_" on the "right" way of organising the array ... e.g. should words be grouped, should there be several arrays e.g: all words starting with "a" in the first array, words starting with "b" in the second, etc.

@scottchiefbaker _agreed_. 👍
