### ISSUE TITLE
the word "pillow" is capitalised

### ISSUE THREAD

**Issue by JoeChen2** [dwyl/english-words#65]
the lower case version don't exist in the text file.

**Comment by nelsonic** [comment]
@JoeChen2 good spot, if you have time, please create a Pull Request to fix it. thanks! ☀️

**Comment by jacebenson** [comment]
I think this is fixed, https://github.com/dwyl/english-words/commit/85e6d09f399772d160fc59ca6e0a48cdb339bd91
