### ISSUE TITLE
What is the difference between words.txt, words2.txt, and words3.txt?

### ISSUE THREAD

**Issue by cameronehrlich** [dwyl/english-words#7]

**Comment by AndrewHannigan** [comment]
Same question.  Is words3 just the latest version?

**Comment by chrisiaut** [comment]
words3 seem to contain the same words multiple times just some with a dot in the end and things like that. For clean words I'd say only use words.txt

**Comment by spookiecookie** [comment]
@chrisiaut  words.txt is good enough. If you like only alpha words see [english-words/words_alpha.txt](url)

**Comment by nelsonic** [comment]
@spookiecookie thanks for helping clarify. 👍 
would be _really_ good to capture this in the README so that other people are aware. 😉

**Comment by spookiecookie** [comment]
I would remove everything except words_alpha.txt and name words_alpha.txt to words.txt. So the users go straight to the point. What do you think?

**Comment by spookiecookie** [comment]
See #11 pull request: moved all from words2.txt, words3.txt to words.txt and removed duplicates then sorted. Removed words2.txt, words3.txt.  
What you want is:
-  [words.txt](english-words/words.txt) contains all words.
-  [words_alpha.txt](english-words/words_alpha.txt) contains only [[:alpha]] words. If you want a quick solution choose this.

**Comment by nelsonic** [comment]
This has now been clarified in the readme so closing the issue. thanks.
