### ISSUE TITLE
2?

### ISSUE THREAD

**Issue by Panama-Hat** [dwyl/english-words#76]
WHY DOES IT START WITH 2? 2 IS NOT A WORD. MY FRIEND AND I HAVE BEEN DRIVEN INSANE THESE LAST FEW DAYS TRYING TO FIGURE OUT A DICTIONARY DEFINITION OF 2 THAT WOULD PERMIT IT TO GO ON THIS LIST. PLEASE PLEASE PLEASE ANSWER QUICKLY. WE HAVE SUNK FAR TOO MUCH TIME INTO THIS AND WE NEED TO KNOW.

**Comment by nelsonic** [comment]
`GOTO`: https://github.com/dwyl/english-words/issues/77#issuecomment-627080383

**Comment by ilan-schemoul** [comment]
I have never seen a github repo with so many sketchy people
