### ISSUE TITLE
Abacaxi is NOT an english word.

### ISSUE THREAD

**Issue by mvrozanti** [dwyl/english-words#90]
This repo is an abacaxi unto itself. Unstarring.

**Comment by nelsonic** [comment]
https://www.merriam-webster.com/dictionary/abacaxi

**Comment by mvrozanti** [comment]
I'm sorry. I'm having a real tough time accepting this. I understand where you're coming from: "if it's on the Merriam Webster, then it must be English" but on the page itself you can see that word is borrowed from Portuguese which in turn borrowed it from Tupi. I also know that discussing whether or not a word belongs to a language or not is pretty useless. However:

The question I think is most useful for this repo at the moment is: "how accurate is or should it be?" and the answer should be on the README. How to measure accuracy you may ask? You could perhaps associate each word entry with the count of occurrences on these famous dictionaries. Or perhaps ONLY exist in this list IF the words belong to ALL these dictionaries. It's up to you.

But let's get a few more examples of words that ARE NOT English in Merriam Webster: 

[titmal does not belong](https://www.merriam-webster.com/dictionary/titmal)
[tooken does not belong](https://www.merriam-webster.com/dictionary/tooken)
[polyuric does not belong](https://www.merriam-webster.com/dictionary/polyurc)
[pinchcommons does not belong](https://www.merriam-webster.com/dictionary/pinchcommons)
[Riva does not belong](https://www.merriam-webster.com/dictionary/Riva)
[she-adventurer does not belong](https://www.merriam-webster.com/dictionary/she-adventurer)
[carrot-pated does not belong](https://www.merriam-webster.com/dictionary/carrot-pated)
[tettery does not belong](https://www.merriam-webster.com/dictionary/tettery)
[entrepas does not belong](https://www.merriam-webster.com/dictionary/entrepas)
[ticket-selling does not belong](https://www.merriam-webster.com/dictionary/ticket-selling)
[Knesseth does not belong](https://www.merriam-webster.com/dictionary/Knesseth)
[Ivanovce does not belong](https://www.merriam-webster.com/dictionary/Ivanovce)
[dealbuminize does not belong](https://www.merriam-webster.com/dictionary/dealbuminize)
[ytterbia does not belong](https://www.merriam-webster.com/dictionary/ytterbia)
[masseterine does not belong](https://www.merriam-webster.com/dictionary/masseterine)
[nondistant does not belong](https://www.merriam-webster.com/dictionary/nondistant)
[blandishingly does not belong](https://www.merriam-webster.com/dictionary/blandishingly)
[teacherhood does not belong](https://www.merriam-webster.com/dictionary/teacherhood)
[hypermorally does not belong](https://www.merriam-webster.com/dictionary/hypermorally)
[twaddlingly does not belong](https://www.merriam-webster.com/dictionary/twaddlingly)
[chechakos does not belong](https://www.merriam-webster.com/dictionary/chechakos)
[Siricius does not belong](https://www.merriam-webster.com/dictionary/Siricius)
[manoeuvred does not belong](https://www.merriam-webster.com/dictionary/manoeuvred)
[Lepargyraea does not belong](https://www.merriam-webster.com/dictionary/Lepargyraea)
[inlet's does not belong](https://www.merriam-webster.com/dictionary/inlet's)
[disbenchment does not belong](https://www.merriam-webster.com/dictionary/disbenchment)
[re-exemption does not belong](https://www.merriam-webster.com/dictionary/re-exemption)
[greeney does not belong](https://www.merriam-webster.com/dictionary/greeney)
[wave-encircled does not belong](https://www.merriam-webster.com/dictionary/wave-encircled)
[caryophylleous does not belong](https://www.merriam-webster.com/dictionary/caryophylleous)
[Leoni does not belong](https://www.merriam-webster.com/dictionary/Leoni)
[keyboard's does not belong](https://www.merriam-webster.com/dictionary/keyboard's)
[twice-appointed does not belong](https://www.merriam-webster.com/dictionary/twice-appointed)
[painter-stainer does not belong](https://www.merriam-webster.com/dictionary/painter-stainer)
[rewardableness does not belong](https://www.merriam-webster.com/dictionary/rewardableness)
[outbleeding does not belong](https://www.merriam-webster.com/dictionary/outbleeding)
[Neisserieae does not belong](https://www.merriam-webster.com/dictionary/Neisserieae)
[ashlered does not belong](https://www.merriam-webster.com/dictionary/ashlered)
[out-soul does not belong](https://www.merriam-webster.com/dictionary/out-soul)
[unpicaresque does not belong](https://www.merriam-webster.com/dictionary/unpicaresque)
[semicallipygian does not belong](https://www.merriam-webster.com/dictionary/semicallipygian)
[subtympanitic does not belong](https://www.merriam-webster.com/dictionary/subtympanitic)
[Krutz does not belong](https://www.merriam-webster.com/dictionary/Krutz)
[Cassondra does not belong](https://www.merriam-webster.com/dictionary/Cassondra)
[Angrist does not belong](https://www.merriam-webster.com/dictionary/Angrist)
[noncontiguously does not belong](https://www.merriam-webster.com/dictionary/noncontiguously)
[aluminosity does not belong](https://www.merriam-webster.com/dictionary/aluminosity)

These inconsistencies suck. 

Do with this information what you will.
