### ISSUE TITLE
need samples for machine learning algorithm

### ISSUE THREAD

**Issue by ProgrammerMan13** [dwyl/english-words#92]
Hello! I just need a big list of sentences, (1000+ words), and preferably imperative sentences, but both statements and questions are Ok. Thank you

**Comment by ProgrammerMan13** [comment]
in txt format

**Comment by nelsonic** [comment]
Sorry, this is not relevant to this repository.
I suggest you extract sentences from a random free e-book from Project Gutenburg https://www.gutenberg.org 👍
