### ISSUE TITLE
"Safe"/Inoffensive word list

### ISSUE THREAD

**Issue by foxt** [dwyl/english-words#95]
Will you consider adding a safer or inoffensive wordlist? Many use cases display words to the user, and some developers might rather that the words included in the list are pretty inoffensive. `words_alpha.txt` contains many words that may be offensive ranging from relatively harmless 'damn' to racial slurs.

My personal use case was generating easy to remember random identifiers, and I wouldn't be happy if one of my users got an ID with a slur or swear in it

**Comment by WAUthethird** [comment]
There are preexisting filter lists online - you could probably apply one of those to the english words list to create a safe list.
I'd assume a whitelist or a blacklist approach would work fine too for your use case? You might only need to use a blacklist.

**Comment by DanAtkinson** [comment]
What are the odds!?

I use the `words_alpha.txt` file for a basic dictionary password generator and this has worked fine for over 3 years. It grabs four words at random from my local copy (changed to remove 1-3 char words and capitalise the first letter of each word) and then randomly sorts them.

However, for two days in a row, it has generated offensive passwords. I removed a bunch of them from my copy of the dictionary yesterday, only for the very same thing to happen today with some more offensive words.

My colleague suggested grepping a children's book which is a reasonable start and, although I don't think @WAUthethird's idea is bad, I'd rather not keep that file list in our repository! It's also very incomplete as some choice words I'd want to filter out aren't there.

**Comment by remram44** [comment]
Duplicate of #63, there are several solutions there

**Comment by foxt** [comment]
(and as such I'll close this with a 3 year later recommendation to use EFF's Diceware word list: https://www.eff.org/dice)
